name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Thay đổi tên nhánh nếu bạn sử dụng nhánh khác

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.17.0'  # Hoặc phiên bản Node.js khác nếu cần

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./build
          publish_branch: gh-pages 
